### ISSUE TITLE
Add Slack notification support.

### ISSUE THREAD

**Issue by influx6** [honeytrap/honeytrap#1]
# Requirements
Honeytrap needs to send notifications to slack with filtering support by:

- Per Message Type using Regular Expression
Slack will be a message channel in honeytrap and will be the means through which will deliver messages to slack, the messages which will be passed into this channel will be filtered based on Regular Expression.

- Per Channel
Slack allows us override the channel destination of a giving message hence allow providing channel name from configuration file to allow notifications for specific channels.

## Questions
How will the filtering for the channels be done, by configuration through a UI or json configuration file?

## Required Clarity
What is the current structure for honeytrap and how will it be supporting filtering and what means will this values be provided for.

**Comment by nl5887** [comment]
the configuration (in toml format) already has other channels (elasticsearch and honeytrap) configured. Here we can add Slack as well. Due to the nature of the messages, we need to filter per channel the type of messages (by regular expression) that will pass the channel. This allows us to have only high level notifications to Slack, and detail information to Elasticsearch.

**Comment by influx6** [comment]
Updated the issue to be precise, I was under the assumption we were building to get notifications from slack but it's clearer we want to make notifications to slack and do it on a per channel and message type basis.

**Comment by influx6** [comment]
# Breakdown 
- Add Slack message delivery as is describe in issue #2

- Add Slack filtering by message channel as is describe in issue #3

- Add Slack filtering by message type as describe in issue #4

**Comment by influx6** [comment]
Merged into restructure
